services:
  Mongo:
    build: 
      context: https://github.com/THD-C/Mongo.git
      secrets:
          - github_token
    image: thd/mongo
    container_name: THD_Mongo
    hostname: Mongo
    restart: unless-stopped
    ports:
      - 27017:27017 
    volumes:
      - MO-Data:/data/db

  Mongo_Manager:
    build: Dockerfile
    image: thd/mongo_manager
    container_name: THD_Mongo_Manager
    hostname: Mongo_Manager
    restart: unless-stopped
    ports:
      - 50052:50051
    depends_on:
      Mongo:
        condition: service_started

secrets:
  github_token:
    file: ./.github_token

volumes:
  MO-Data: