name: Release Service

on:
  push:
    branches: main
    paths:
      - '**/*.py'
      - requirements.txt

  workflow_dispatch:
  

permissions:
  contents: write

jobs:
  Release:
    uses: THD-C/GH_Actions/.github/workflows/release.yml@main
    secrets: inherit
    with:
      ServiceRepository: ${{ github.repository }}
